### ISSUE TITLE
Correcciones, pre-entrega

### ISSUE THREAD

**Issue by ChiaCosentino** [rociopaone/portfolio#1]
Acordate de poner siempre, en el head de todos los htmls, la etiqueta de meta viewport. Si no ponés esa etiqueta, no te va a funcionar el responsive!!
![image](https://github.com/rociopaone/portfolio/assets/144492992/eaa80116-ada3-4937-90c0-527f466c020a)
![image](https://github.com/rociopaone/portfolio/assets/144492992/bf6e9ae8-b8be-4b7b-9c4a-57963378754a) *Esta es la etiqueta que tenés que agregar ahí adentro*

Fijate que en las imagenes nombradas así, se te escapó un espacio
![image](https://github.com/rociopaone/portfolio/assets/144492992/849b0c22-5de7-4794-a78c-6d7d7a6a73d0)

En el footer (y en el header) no se usan articles ni sections, sólo se usan divs. Tampoco pueden haber h1s en el footer. Acordate que sólo hay un h1 por html, y que es la información más importante de ese html, como tu nombre o el título la página (por ej si dijese contacto). En general, los títulos del footer suelen ser los h de jerarquía más baja que manejas.
![image](https://github.com/rociopaone/portfolio/assets/144492992/12bf047b-9d2b-4b0f-ba83-169067ca30aa)

**Comment by rociopaone** [comment]
genial! ya corregi estos errores
